<a href="https://colab.research.google.com/github/MHZur/Diplomado_Publico/blob/main/Tareas/Data_Analyst_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Analyst Interview Notebook

## Introduction

This notebook is designed to simulate real-world data that you could see from our technology.

It is designed to test your proficiency with Python and Pandas, and your ability to find and present insights.

This data is confidential; we expect you to not share this data with anyone. And we expect you to not get any external assistance.



---


You are working with a US retail customer on a pilot deployment.  They are using technology to track their merchandise throughout their supply chain.  The flow of their supply is:

*   **DC 1:**  Orders are filled and palletized.
*   **Truck:** Pallets travel from the DC 1 to DC 2 via semi-truck.
*   **DC 2:**  Pallets are unloaded, and additional merchandise may be added.  They are then reloaded onto a new truck.
*   **Truck:** Pallets travel from DC 2 to the Store.
*   **Store:** Pallets are unloaded, cases are removed, and stocked, and the empty cases are left behind the building awaiting pickup.

Your job is to dig into the data and find compelling insights to show the value fo the technology and help move the contract from a pilot into a full scaled deployment.



---

Each section has defined questions along with point values to help you prioritize your time.

In addition to the defined questions, the overall notebook and code presentation will be evaluated, and you will be awarded up to 10 points based on the clarity, cleaniness, and efficiency of the code.

## Part 0: Imports

Import necessary packages and

In [ ]:
# YOUR CODE HERE:
import pandas as pd
from google.colab import drive
import plotly.io as pio
import plotly.express as px
import numpy as np

In [ ]:
drive.mount("/content/drive")
%cd /content/drive/My \Drive/Diplomado

Mounted at /content/drive
/content/drive/My Drive/Diplomado

In [ ]:
df = pd.read_excel("tote_shipment.xlsx")
df.head()

,asset_type,asset_id,tag_id,Site,Zone,device_id,time_est,lat,lng,Temperature_C,Temperature_F
0,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:59:26.628,47.79158,-65.68902,23.0,73.4
1,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,EC5B0499234F,2022-08-02 12:00:22.660,47.79158,-65.68902,23.0,73.4
2,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 12:01:11.234,47.79158,-65.68902,23.0,73.4
3,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,3D8B2BDB8673,2022-08-02 13:47:58.172,47.79158,-65.68902,23.5,74.3
4,tote,2,(01)00850027865010(21)0082T0670,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:58:55.049,47.79158,-65.68902,23.0,73.4

In [ ]:
df.asset_id.unique()

array([  2,  37,  52,  58,  59,  62,  70,  84, 102, 145, 149, 159, 167,
       170, 181, 182, 200, 205])

In [ ]:
df.Site.unique()

array(['DC 1', 'DC 2', 'Transit', 'Store'], dtype=object)

### Dataset Overview

* Site:  A large space that could contain multiple readers. Ex: DC 1.
* Zone:  Point of interest. These represent areas in which repeaters are installed. These can be thought of as sub-zones.  Ex: Dock Doors.
* Asset ID: The unique ID of the asset.
* Asset Type: The type of thing that is detected (ie tote).
* Device ID: The unique gateway reader ID that detected the device in the zone (there can be multiple in one zone).
* Time est: The time in EST.
* Lon: Longituge
* Lat: Latitude
* Temperature_C / F: Temperature in Celsius, Fahrentheit

## PART 1: Data Overview

### Question 1:

* How many unique cases were we tracking throughout this pilot. (1 pt)
* What are the unique zones we could see (1 pt)
* How many POI's are in each Zone. (2 pts)

In [ ]:
# YOUR CODE HERE:
print(f"Unique cases: {len(df['asset_id'].unique())}")

print(f"Unique zones: {df['Zone'].unique()}")

Unique cases: 18
Unique zones: ['dock_doors_DC1' 'dock_doors_DC2' 'Forklift3_DC1' 'pallet_assembly_DC1'
 'PhoneKit1Bridge' 'PhoneKit2Bridge' 'PhoneKit2GW' 'point_of_sale_Store'
 'receiving_Store' 'staging_DC1' 'staging_DC2' 'store_back_Store'
 'store_front_Store' 'Forklift1_DC1' 'PhoneKit1GW']

### Question 2:

* What is the temperature range we see?  (1pt)
* Where is temperature the highest and lowest (1pt)

In [ ]:
# YOUR CODE HERE:
print(f"Rango de temperatura: {df['Temperature_C'].max() - df['Temperature_C'].min()}")
print(f"Máximo: {df['Temperature_C'].max()}")
print(f"Mínimo: {df['Temperature_C'].min()}")

Rango de temperatura: 25.0
Máximo: 44.0
Mínimo: 19.0

## Part 2: The Journey of a Case

### Question 3:

* Create a visualization that shows where a case was at over time at the zone or POI level. Imagine that this would be included in your presentation to the customer. (Non techical audience) (3 pts)

In [ ]:
# FILTRAMOS LA DATA PARA GRAFICAR UN CASO PARTICULAR (2,  37,  52,  58,  59,  62,  70,  84, 102, 145, 149, 159, 167, 170, 181, 182, 200, 205)
df_visualization = df[df.asset_id == 2].copy()
df_visualization

,asset_type,asset_id,tag_id,Site,Zone,device_id,time_est,lat,lng,Temperature_C,Temperature_F
0,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:59:26.628,47.791580,-65.689020,23.0,73.4
1,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,EC5B0499234F,2022-08-02 12:00:22.660,47.791580,-65.689020,23.0,73.4
2,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 12:01:11.234,47.791580,-65.689020,23.0,73.4
3,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,3D8B2BDB8673,2022-08-02 13:47:58.172,47.791580,-65.689020,23.5,74.3
4,tote,2,(01)00850027865010(21)0082T0670,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:58:55.049,47.791580,-65.689020,23.0,73.4
...,...,...,...,...,...,...,...,...,...,...,...
6764,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:00:28.894,47.749230,-65.641010,22.0,71.6
6765,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:00:50.535,47.749230,-65.641010,22.0,71.6
6766,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:01:28.268,47.749230,-65.641010,22.0,71.6
6767,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:02:57.199,47.749388,-65.640811,22.0,71.6
6768,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:04:58.575,47.749230,-65.641010,22.0,71.6

In [ ]:
# YOUR CODE HERE:
df_visualization_g1 = df_visualization.groupby(["Zone"])[["time_est"]].min().sort_values(by = ["time_est"]).reset_index()
df_visualization

,asset_type,asset_id,tag_id,Site,Zone,device_id,time_est,lat,lng,Temperature_C,Temperature_F
0,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:59:26.628,47.791580,-65.689020,23.0,73.4
1,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,EC5B0499234F,2022-08-02 12:00:22.660,47.791580,-65.689020,23.0,73.4
2,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 12:01:11.234,47.791580,-65.689020,23.0,73.4
3,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,3D8B2BDB8673,2022-08-02 13:47:58.172,47.791580,-65.689020,23.5,74.3
4,tote,2,(01)00850027865010(21)0082T0670,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:58:55.049,47.791580,-65.689020,23.0,73.4
...,...,...,...,...,...,...,...,...,...,...,...
6764,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:00:28.894,47.749230,-65.641010,22.0,71.6
6765,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:00:50.535,47.749230,-65.641010,22.0,71.6
6766,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:01:28.268,47.749230,-65.641010,22.0,71.6
6767,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:02:57.199,47.749388,-65.640811,22.0,71.6
6768,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:04:58.575,47.749230,-65.641010,22.0,71.6

In [ ]:
# Calculate the difference between rows - periods = 2

df_visualization_g1["time_spent"] = df_visualization_g1["time_est"].diff(periods=1)

df_visualization_g1

                   Zone                time_est             time_spent
0   pallet_assembly_DC1 2022-08-02 10:59:58.887                    NaT
1           staging_DC1 2022-08-02 11:46:53.446 0 days 00:46:54.559000
2        dock_doors_DC1 2022-08-02 11:58:55.049 0 days 00:12:01.603000
3         Forklift3_DC1 2022-08-02 12:02:27.028 0 days 00:03:31.979000
4       PhoneKit1Bridge 2022-08-02 13:52:30.665 0 days 01:50:03.637000
5           PhoneKit2GW 2022-08-02 14:29:24.919 0 days 00:36:54.254000
6       PhoneKit2Bridge 2022-08-02 14:46:16.221 0 days 00:16:51.302000
7        dock_doors_DC2 2022-08-03 10:59:28.892 0 days 20:13:12.671000
8           staging_DC2 2022-08-04 03:39:20.359 0 days 16:39:51.467000
9       receiving_Store 2022-08-04 08:35:16.191 0 days 04:55:55.832000
10     store_back_Store 2022-08-04 08:37:46.719 0 days 00:02:30.528000
11    store_front_Store 2022-08-04 08:39:43.562 0 days 00:01:56.843000
12  point_of_sale_Store 2022-08-04 10:55:21.122 0 days 02:15:37.560000

In [ ]:
fig = px.line(df_visualization_g1, x = 'time_est', y = 'Zone', markers = True)
fig.update_layout(
    xaxis_title = 'Fecha-Hora',
    yaxis_title = 'Zona',
    template = 'plotly_white',
    )
fig

#La gráfica nos muestra los momentos en que el objeto cambió de zona.

### Question 4:

* Visualize how the temperatue changes over time along its journey.  Imagine that this would be included in your presentation to the customer. (Non techical audience) (4 pts)

In [ ]:
# YOUR CODE HERE:
df_grafica_temp = df_visualization.groupby(["Zone"]).agg({"time_est": np.min, "Temperature_C": np.mean}).sort_values(by = ["time_est"]).reset_index()
df_grafica_temp

                   Zone                time_est  Temperature_C
0   pallet_assembly_DC1 2022-08-02 10:59:58.887      22.722656
1           staging_DC1 2022-08-02 11:46:53.446      23.298611
2        dock_doors_DC1 2022-08-02 11:58:55.049      23.100000
3         Forklift3_DC1 2022-08-02 12:02:27.028      23.444444
4       PhoneKit1Bridge 2022-08-02 13:52:30.665      25.000000
5           PhoneKit2GW 2022-08-02 14:29:24.919      25.346154
6       PhoneKit2Bridge 2022-08-02 14:46:16.221      25.340909
7        dock_doors_DC2 2022-08-03 10:59:28.892      24.937500
8           staging_DC2 2022-08-04 03:39:20.359      25.000000
9       receiving_Store 2022-08-04 08:35:16.191      26.209462
10     store_back_Store 2022-08-04 08:37:46.719      23.197803
11    store_front_Store 2022-08-04 08:39:43.562      23.764593
12  point_of_sale_Store 2022-08-04 10:55:21.122      22.583333

### Question 5:
* Visualize the lon lat data on a map to show how the case traveled.  You may incorporate any other additional information to make this more impactful. Imagine that this would be included in your presentation to the customer. (Non techical audience) (5 pts)

**Do not worry if this looks like non-sense on a map.  Ex:  The trip may appear to occur over water or in a forest because this is a toy dataset.**

In [ ]:
df_visualization

,asset_type,asset_id,tag_id,Site,Zone,device_id,time_est,lat,lng,Temperature_C,Temperature_F
0,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:59:26.628,47.791580,-65.689020,23.0,73.4
1,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,EC5B0499234F,2022-08-02 12:00:22.660,47.791580,-65.689020,23.0,73.4
2,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 12:01:11.234,47.791580,-65.689020,23.0,73.4
3,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,3D8B2BDB8673,2022-08-02 13:47:58.172,47.791580,-65.689020,23.5,74.3
4,tote,2,(01)00850027865010(21)0082T0670,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:58:55.049,47.791580,-65.689020,23.0,73.4
...,...,...,...,...,...,...,...,...,...,...,...
6764,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:00:28.894,47.749230,-65.641010,22.0,71.6
6765,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:00:50.535,47.749230,-65.641010,22.0,71.6
6766,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:01:28.268,47.749230,-65.641010,22.0,71.6
6767,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:02:57.199,47.749388,-65.640811,22.0,71.6
6768,tote,2,(01)00850027865010(21)0082T0670,Store,store_front_Store,6AF833197EE3,2022-08-05 09:04:58.575,47.749230,-65.641010,22.0,71.6

In [ ]:
# YOUR CODE HERE:
df_visualization_map = df_visualization.groupby(["Zone"]).agg({"time_est": np.min, "lat": np.min, "lng":np.min}).sort_values(by = ["time_est"]).reset_index()

df_visualization_map

                   Zone                time_est       lat       lng
0   pallet_assembly_DC1 2022-08-02 10:59:58.887  47.79158 -65.68965
1           staging_DC1 2022-08-02 11:46:53.446  47.79158 -65.68962
2        dock_doors_DC1 2022-08-02 11:58:55.049  47.79158 -65.68902
3         Forklift3_DC1 2022-08-02 12:02:27.028  47.79158 -65.68902
4       PhoneKit1Bridge 2022-08-02 13:52:30.665  47.74923 -65.76023
5           PhoneKit2GW 2022-08-02 14:29:24.919  47.74900 -65.75989
6       PhoneKit2Bridge 2022-08-02 14:46:16.221  47.76429 -65.76047
7        dock_doors_DC2 2022-08-03 10:59:28.892  47.79366 -65.75921
8           staging_DC2 2022-08-04 03:39:20.359  47.79366 -65.75921
9       receiving_Store 2022-08-04 08:35:16.191  47.74899 -65.64101
10     store_back_Store 2022-08-04 08:37:46.719  47.74923 -65.64101
11    store_front_Store 2022-08-04 08:39:43.562  47.74902 -65.64101
12  point_of_sale_Store 2022-08-04 10:55:21.122  47.74923 -65.64101

In [ ]:
fig = px.scatter_mapbox(df_visualization_map, lat="lat", lon="lng", hover_name="Zone", height=600,
                        center = {"lat":47.76, "lon":-65.7}, mapbox_style='open-street-map', zoom =11)

fig.show()

# Part 3: Customer Questions

### Question 6:

The customer wants to understand the efficieny of ther DC operations.
* Based on what you see in the data, (all zones except for STORE), which parts of their operation are most & least "efficient? (10 pts)

In [ ]:
df

,asset_type,asset_id,tag_id,Site,Zone,device_id,time_est,lat,lng,Temperature_C,Temperature_F
0,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:59:26.628,47.79158,-65.68902,23.0,73.40
1,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,EC5B0499234F,2022-08-02 12:00:22.660,47.79158,-65.68902,23.0,73.40
2,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 12:01:11.234,47.79158,-65.68902,23.0,73.40
3,tote,2,(01)00850027865010(21)0082T0219,DC 1,dock_doors_DC1,3D8B2BDB8673,2022-08-02 13:47:58.172,47.79158,-65.68902,23.5,74.30
4,tote,2,(01)00850027865010(21)0082T0670,DC 1,dock_doors_DC1,7F9A8353E973,2022-08-02 11:58:55.049,47.79158,-65.68902,23.0,73.40
...,...,...,...,...,...,...,...,...,...,...,...
130056,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:48:51.273,47.74923,-65.64101,23.1,73.58
130057,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:49:58.699,47.74923,-65.64101,23.5,74.30
130058,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:52:45.173,47.74923,-65.64101,23.0,73.40
130059,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 12:53:48.228,47.74923,-65.64101,23.0,73.40
130060,tote,205,(01)00850027865010(21)0082T1137,Store,store_front_Store,26AB1C9A2E41,2022-08-04 16:33:25.525,47.74923,-65.64101,24.0,75.20

In [ ]:
# YOUR CODE HERE
df_operations = df[~(df["Zone"].str.contains(pat = "store"))].groupby(["Zone", "asset_id"]).agg(Max=("time_est", np.max), Min=("time_est",np.min)).reset_index()

df_operations["total_time"] = df_operations["Max"] - df_operations["Min"]

df_operations = df_operations.groupby(["Zone"]).agg(Sum = ("total_time", np.sum))

mejor_tiempo = df_operations["Sum"].min()
mejor_zona = df_operations[df_operations["Sum"] == mejor_tiempo].reset_index()["Zone"][0]

peor_tiempo = df_operations["Sum"].max()
peor_zona = df_operations[df_operations["Sum"] == peor_tiempo].reset_index()["Zone"][0]

print(f"La mejor zona es {mejor_zona} con un tiempo total de: {mejor_tiempo}")
print(f"La peor zona es {peor_zona} con un tiempo total de: {peor_tiempo}")

La mejor zona es dock_doors_DC1 con un tiempo de: 0 days 07:58:22.396000
La peor zona es PhoneKit1Bridge con un tiempo de: 30 days 19:43:02.909000

YOUR TEXT ANSWER HERE

### Question 7:

The customer wants to understand the stocking efficiency in stores.
* Based on what you see in the data, how quickly did the store unload and stock the merchandise. (5 pts)
* How could this be converted in a KPI that a regional manager could track?  (5 pts)

In [ ]:
#POI de las tiendas
df_7 = df[df.Site == "Store"].groupby("asset_id").agg(Max=("time_est", np.max), Min=("time_est",np.min)).reset_index()

df_7["Tiempo_Utilizado"] = df_7["Max"] - df_7["Min"]

df_7

,asset_id,Max,Min,Tiempo_Utilizado
0,2,2022-08-05 13:28:24.536,2022-08-04 08:35:16.191,1 days 04:53:08.345000
1,37,2022-08-05 13:28:18.117,2022-08-04 08:35:50.815,1 days 04:52:27.302000
2,52,2022-08-05 13:28:29.966,2022-08-04 08:35:55.812,1 days 04:52:34.154000
3,58,2022-08-05 13:28:25.606,2022-08-04 08:36:33.479,1 days 04:51:52.127000
4,59,2022-08-05 13:28:28.576,2022-08-04 08:35:58.390,1 days 04:52:30.186000
5,62,2022-08-05 13:28:25.543,2022-08-04 08:35:43.433,1 days 04:52:42.110000
6,70,2022-08-05 13:28:05.827,2022-08-04 08:35:20.926,1 days 04:52:44.901000
7,84,2022-08-05 13:28:18.168,2022-08-04 08:38:07.889,1 days 04:50:10.279000
8,102,2022-08-05 13:28:20.877,2022-08-04 08:38:50.511,1 days 04:49:30.366000
9,145,2022-08-05 13:28:23.036,2022-08-04 08:46:59.487,1 days 04:41:23.549000
10,149,2022-08-05 13:28:20.650,2022-08-04 08:46:16.496,1 days 04:42:04.154000
11,159,2022-08-05 13:28:14.655,2022-08-04 08:46:21.336,1 days 04:41:53.319000
12,167,2022-08-05 13:28:26.584,2022-08-04 08:46:23.725,1 days 04:42:02.859000
13,170,2022-08-05 13:28:25.330,2022-08-04 08:46:28.293,1 days 04:41:57.037000
14,181,2022-08-05 13:28:28.172,2022-08-04 08:46:29.340,1 days 04:41:58.832000
15,182,2022-08-05 13:28:17.200,2022-08-04 08:46:47.644,1 days 04:41:29.556000
16,200,2022-08-05 13:28:27.564,2022-08-04 08:46:29.453,1 days 04:41:58.111000
17,205,2022-08-05 13:27:29.798,2022-08-04 08:46:18.909,1 days 04:41:10.889000

In [ ]:
# Para convertirlo en un kpi se pueden separ los tiempos en las distintas zonas y ver en porcentajes que lugar ocupan las tiendas con respecto a las demás y frente al total.
kpi_tiempo = df_7["Tiempo_Utilizado"].mean()
kpi_tiempo = str(kpi_tiempo)
print("El tiempo promedio empleado en la tienda es de: ", kpi_tiempo)

El tiempo promedio empleado en la tienda es de:  1 days 04:46:52.115333333

YOUR TEXT ANSWER HERE

### Question 8:

Please explain what you would ask for and what you will do with this data, given that you can talk with the following people (no code needed):

YOUR TEXT ANSWER HERE
* a. Las temperaturas recomendadas a las que deben de estar los objetos que se están transportando para saber si en algún punto del traslado no se tenía la temperatura deseada y por cuanto tiempo fue esto.

## Part 4: Bonus Insights

### Question 8

The customer is open to hearing about additional insights you found in the data above and beyond what they asked for.
* Based on what you can see in the data, are there any other interesting insights that the customer may want to hear about? (Up to 15 bonus points)

In [ ]:
# YOUR CODE HERE
# Another metrics that could be interesting would be temperature by time

YOUR TEXT ANSWER HERE